name: Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup and run linter
      run: |
        pip install cpplint
        cpplint  --filter=-legal --linelength=100 *.cpp

    - name: tshirts fail
      run: |
        g++ -Wall -Wextra -Werror TShirtsSizeCalculator.cpp TShirtsSizeMain.cpp TShirtsSizeTests.cpp -o tshirts.out
        ./tshirts.out

    - name: misaligned fail
      run: |
        g++ -Wall -Wextra -Werror ColorMapAlignmentTest.cpp ColorMap.cpp -o ColorMapAlignmentTest.out
        ./ColorMapAlignmentTest.out

    - name: alerter fail
      run: |
        g++ -Wall -Wextra -Werror weatherreport.cpp weatherreportMain.cpp weatherreportTests.cpp SensorStub.cpp -o weatherreport.out
        ./weatherreport.out
