name: Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup and run linter
      run: |
        pip install cpplint
        cpplint  --filter=-legal --linelength=100 *.cpp

    - name: tshirts fail
      run: |
        g++ -Wall -Wextra -Werror tshirts.cpp -o tshirts.out
        # bash .github/workflows/expectfail.sh 
        ./tshirts.out

    - name: misaligned fail
      run: |
        g++ -Wall -Wextra -Werror color_map_alignmentTest.cpp color_map.cpp -o color_map_alignmentTest.out
        # bash .github/workflows/expectfail.sh 
        ./color_map_alignmentTest.out

    - name: alerter fail
      run: |
        g++ -Wall -Wextra -Werror weatherreport.cpp weatherreportMain.cpp weatherreportTests.cpp SensorStub.cpp -o weatherreport.out
        # bash .github/workflows/expectfail.sh 
        ./weatherreport.out
